LINQExamples/Models/Author.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LINQExamples.Models
{
    public class Author
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
}

LINQExamples/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LINQExamples.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
}

LINQExamples/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LINQExamples.Models
{
    public class Product
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public decimal Price { get; set; }

        public virtual Category Category { get; set; }

        public DateTime Publish { get; set; }

        public virtual Author Author { get; set; }
    }
}

LINQExamples/Models/ProductContext.cs
namespace LINQExamples.Models
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class ProductContext : DbContext
    {
        public ProductContext()
            : base("name=ProductContext")
        {
        }

        public DbSet<Product> Products { get; set; }
        public DbSet<Category> Categories { get; set; }

        public DbSet<Author> Authors { get; set; }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    }
}

LINQExamples/Controllers/FilterController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LINQExamples.Models;

namespace LINQExamples.Controllers
{
    public class FilterController : Controller
    {
        // GET: Filter
        public ActionResult Index()
        {
            var db = new ProductContext();
           
            // grouping
            var products = db.Products.GroupBy(p => p.Price).ToList();

            var vm = new Tuple<List<IGrouping<decimal, Product>>>(products);


            return View(vm);
        }

        public ActionResult Search(string id = "", string title = "", string description = "", string columnOrderByName = "", bool isDesc = true)
        {
            var db = new ProductContext();

            // Searching
            List<Product> products = db.Products.Where(product => product.Title.Contains(title)
                                                        && product.Id.ToString().Contains(id)
                                                        && product.Description.Contains(description)).ToList();

            // Order by 
            if (!string.IsNullOrWhiteSpace(columnOrderByName))
            {
                if (isDesc)
                {
                    PropertyDescriptor prop = TypeDescriptor.GetProperties(typeof(Product))
                        .Find(columnOrderByName, true);
                    products = products.OrderByDescending(p => prop.GetValue(p)).ToList();
                }
                else
                {
                    PropertyDescriptor prop = TypeDescriptor.GetProperties(typeof(Product))
                        .Find(columnOrderByName, true);
                    products = products.OrderBy(p => prop.GetValue(p)).ToList();
                }
            }

            var vm = new Tuple<List<Product>>(products);


            return View(vm);
        }
    }
}

LINQExamples/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LINQExamples.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LINQExamples/Views/Filter/Index.cshtml
@model  Tuple<List<IGrouping<decimal, LINQExamples.Models.Product >>>
@{
    ViewBag.Title = "Index";
    int i = 0;
}

<h2>Products</h2>

@foreach (var group in Model.Item1)
{
    <h2>@i</h2>
    <table class="table">
        <tr>
            <th>
                Id
            </th>

            <th>
                Title
            </th>

            <th>
                Description
            </th>

            <th>
                Price
            </th>

            <th>
                Category
            </th>

            <th>
                Author
            </th>

        </tr>
        <tr>
            <th>
                <input id="Id" type="text" value=""/>
            </th>
            <th>
                <input id="Title" type="text" value=""/>
            </th>
            <th>
                <input id="Description" type="text" value=""/>
            </th>
            <th>
                <input id="Price" type="text" value=""/>
            </th>
            <th>
                <select id="Category">
                    <option></option>
                </select>
            </th>
            <th>
                <select id="Author">
                    <option></option>
                </select>
            </th>
        </tr>

        @foreach (var product in group)
        {
            <tr>
                <td>
                    @product.Id
                </td>
                <td>
                    @product.Title
                </td>
                <td>
                    @product.Description
                </td>
                <td>
                    @product.Price
                </td>
                <td>
                    @product.Category.Name
                </td>
                <td>
                    @product.Author.Name
                </td>
            </tr>
        }
    </table>

    i++;
}

LINQExamples/Views/Filter/Search.cshtml
@model  Tuple<List<LINQExamples.Models.Product>>
@{
    ViewBag.Title = "Index";
    int i = 0;
}

<h2>Products</h2>


@using (Html.BeginForm("Search", "Filter", FormMethod.Get))
{
    <table class="table">
        <tr>
            <th>
                Id
                
                <a href="#" class="orderby" data-column="Id">order ME!</a>
            </th>

            <th>
                Title
                
                <a href="#" class="orderby" data-column="Title">order ME!</a>
            </th>

            <th>
                Description
                
                <a href="#" class="orderby" data-column="Description">order ME!</a>
            </th>

            <th>
                Price
                
                <a href="#" class="orderby" data-column="Price">order ME!</a>
            </th>

            <th>
                Category
                
                <a href="#" class="orderby" data-column="Category">order ME!</a>
            </th>

            <th>
                Author
                
                <a href="#" class="orderby" data-column="Author">order ME!</a>
            </th>

        </tr>
        <tr>
            <th>
                <input id="Id" name="Id" type="text" value=""/>
            </th>
            <th>
                <input id="Title" name="TItle" type="text" value=""/>
            </th>
            <th>
                <input id="Description" name="Description" type="text" value=""/>
            </th>
            <th>
                <input id="Price" name="Price" type="text" value=""/>
            </th>
            <th>
                <select id="Category" name="Category">
                    <option></option>
                </select>
            </th>
            <th>
                <select id="Author" name="Author">
                    <option></option>
                </select>
            </th>
        </tr>
        
        <tr>
            <td colspan="6">
                <button>Search</button>
            </td>
        </tr>

        @foreach (var product in Model.Item1)
        {
            <tr>
                <td>
                    @product.Id
                </td>
                <td>
                    @product.Title
                </td>
                <td>
                    @product.Description
                </td>
                <td>
                    @product.Price
                </td>
                <td>
                    @product.Category.Name
                </td>
                <td>
                    @product.Author.Name
                </td>
            </tr>
        }
    </table>
}

@section scripts {
    
    <script>

        $(".orderby").click(function (e) {
            var columnName = $(this).data("column");
            var params = $.url().param(); // purl js script
           
            params["columnOrderByName"] = columnName;
  
            if (params["isDesc"] == "true") {
                params["isDesc"] = false;
            } else {
                params["isDesc"] = true;
            }

            window.location = "?" + $.param(params);

            e.preventDefault();
        });

        //$("form").submit(function() {

        //    window.location = 
        //});
            

    </script>
}

LINQExamples/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

LINQExamples/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LINQExamples/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

LINQExamples/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/purl.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>